#!/usr/bin/env python3
"""Generate kernel-checked correspondence lemmas for all 69,120 byte rows.

Python writes proof scripts only. Every equality with the concrete export is
proved by Lean's kernel via `decide`, using the proved coefficient-code decoder.
"""
import argparse
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'lean/CircuitCorrectness/ByteCertificates'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
CHECK = parser.parse_args().check
if not CHECK:
    OUT.mkdir(exist_ok=True)
def emit(path, text):
    if CHECK:
        if not path.exists() or path.read_text() != text:
            raise SystemExit(f'Generated byte certificate drift: {path}')
    else:
        path.write_text(text)
for g in range(27):
    imports=['import CircuitCorrectness.ByteCertificates.Decode']
    if g >= 4:
        imports.append(f'import CircuitCorrectness.ByteCertificates.Group{g-4:02d}')
    lines=imports+['', 'set_option maxRecDepth 100000', 'set_option maxHeartbeats 10000000',
                   'namespace CircuitCorrectness.ConcreteBytes', '']
    for c in range(20*g,20*(g+1)):
        lines += [f'theorem chunk{c:03d} :',
            f'    Exported.decodeRows ExportedData.chunk{c}.1 ExportedData.chunk{c}.2 =',
            f'      (List.range 128).map (fun i => byteRow ({128*c} + i)) := by',
            f'  exact Codes.certificate {c} ExportedData.chunk{c} (by decide)', '']
    lines += [f'theorem group{g:02d} (c : Fin 20) :',
        f'    let chunk := ExportedData.chunks[{20*g} + c.val]!',
        '    Exported.decodeRows chunk.1 chunk.2 =',
        f'      (List.range 128).map (fun i => byteRow (128*({20*g} + c.val) + i)) := by',
        '  fin_cases c']
    for c in range(20*g,20*(g+1)):
        lines += [f'  · exact chunk{c:03d}']
    lines += ['', 'end CircuitCorrectness.ConcreteBytes','']
    emit(OUT/f'Group{g:02d}.lean', '\n'.join(lines))
print('Checked' if CHECK else 'Wrote', '540 exact chunk certificates in 27 grouped Lean modules.')
# The exported image-wire table is also checked in bounded kernel reductions.
for g in range(12):
    dependency = 'PixelBase' if g == 0 else f'PixelGroup{g-1:02}'
    text = f'import CircuitCorrectness.ByteCertificates.{dependency}\n'
    text += 'set_option maxRecDepth 100000\nset_option maxHeartbeats 10000000\n'
    text += 'namespace CircuitCorrectness.ConcreteBytes\n'
    for c in range(5*g,5*g+5):
        text += f'theorem pixel_chunk_{c} : ExportedData.pixelChunk{c} = expectedPixelChunk {c} := by rfl\n'
    text += 'end CircuitCorrectness.ConcreteBytes\n'
    emit(OUT/f'PixelGroup{g:02}.lean',text)
print('Checked' if CHECK else 'Wrote', '60 exact pixel-wire chunk certificates in 12 grouped Lean modules.')
